Update deploy to production.yml

diff --git a/.github/workflows/deploy to production.yml b/.github/workflows/deploy to production.yml
--- a/.github/workflows/deploy to production.yml
+++ b/.github/workflows/deploy to production.yml
@@ -48,9 +48,10 @@ jobs:
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key azureuser@168.61.83.8 "echo 'SSH Connection Successful'"
 
     # Kill the process on the VM (if running)
-    #- name: Kill running process
-    #  run: |
-    #    ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key azureuser@168.61.83.8 "sudo pkill -f ShelfSenseBE-0.0.1-SNAPSHOT.jar || true"
+    - name: Kill running process
+      run: |
+        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key azureuser@168.61.83.8 "pgrep -f ShelfSenseBE-0.0.1-SNAPSHOT.jar && sudo pkill -9 ShelfSenseBE-0.0.1-SNAPSHOT.jar || echo 'No process found to kill'"
+
 
     # Delete the old JAR file
     - name: Delete old JAR file
@@ -65,4 +66,4 @@ jobs:
     # Run the new JAR file
     - name: Run new JAR file
       run: |
-        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key azureuser@168.61.83.8 "nohup java -jar ShelfSenseBE-0.0.1-SNAPSHOT.jar &"
+        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key azureuser@168.61.83.8 "nohup java -jar ShelfSenseBE-0.0.1-SNAPSHOT.jar > app.log 2>&1 & sleep 15 && pgrep -f ShelfSenseBE-0.0.1-SNAPSHOT.jar && echo 'JAR started successfully' || echo 'Failed to start JAR' && exit 1"
